// AUTO-GENERATED from tests/fixtures/journey/ by scripts/gen_skills.py - do not edit.
// The journeys journey.py is tested against, so the mod reads the same shapes.

export const FIXTURES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "asks": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on that have not been verified. A-1 to\nA-3 and A-7 are asks of people outside the design; A-5 reads like one but has\nnot been routed; A-6 is settled inside it.\n\n| ID | Assumption | Source | Validates it | Depends on it | Status | Status date |\n|---|---|---|---|---|---|---|\n| A-1 | Depots open at 06:00 on weekdays | courier interviews | Ask Depot operations: the opening-hours list per depot | ADR-0005 | Open | 2026-03-10 |\n| A-2 | Locker controllers report door state within a second | vendor sheet | Ask Locker vendor: the firmware's reporting interval | ADR-0004, S-12 | Open | 2026-03-20 |\n| A-3 | A locker bank survives a 30-second power cut | vendor sheet | Ask Locker vendor team: the UPS hold-up time | R2 | Partly resolved | 2026-04-10 |\n| A-4 | Couriers carry a phone with mobile data | depot manager | Ask Depot operations: the device policy | ADR-0002 | Resolved | 2026-04-01 |\n| A-5 | Parcel labels carry the locker bank ID | label sample | confirm with the courier partner's integration owner | ADR-0006 | Open | 2026-04-05 |\n| A-6 | Reservation lookups stay under 50 ms | inference | a load test against the staging API | ADR-0003 | Open | 2026-04-06 |\n| A-7 | Door unlock codes are single use | design | Ask Security: a pen test of the unlock endpoint | R1 | Resolved by design (test pending) | 2026-04-08 |\n\n## Status lines\n\n- A-1 · Open · 2026-03-10 · registered\n- A-2 · Open · 2026-03-20 · registered\n- A-2 · Open · 2026-04-02 · asked Locker vendor\n- A-3 · Open · 2026-03-22 · registered\n- A-3 · Open · 2026-03-25 · asked Locker vendor team\n- A-3 · Partly resolved · 2026-04-10 · vendor confirmed a UPS, not its hold-up time\n- A-3 · Partly resolved · 2026-04-15 · asked Locker vendor team\n- A-4 · Open · 2026-03-12 · registered\n- A-4 · Resolved · 2026-04-01 · depot operations sent the device policy\n- A-5 · Open · 2026-04-05 · registered\n- A-6 · Open · 2026-04-06 · registered\n- A-7 · Open · 2026-04-07 · registered\n- A-7 · Resolved by design (test pending) · 2026-04-08 · single-use codes in the design\n",
    "decisions-log.md": "# Decisions Log\n\nEvery gate and every brief, numbered journey-wide.\n\n## D1 · 2026-03-01 · Terrain\n\n- **Gate:** terrain\n- **Answer:** Greenfield\n- **Rationale:** no locker system exists yet.\n- **Changes the actor set:** no\n- **Supersedes:** —\n\n## 2026-03-15 · Vendor workshop held, no brief\n\nThe locker vendor walked the controller firmware; notes in discovery. The\nfollow-up is D2.\n\n## D2 · 2026-03-20 · Iterate after iteration 1\n\n- **Gate:** iterate\n- **Answer:** iterate\n- **Rationale:** the courier walk found two new actors.\n- **Changes the actor set:** no\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State: Lockerline\n\n**Implementation status:** Design-only — nothing implemented\n**Design boundary:** the reservation service and the locker controller; the courier app is a handoff ask\n\n## Current Position\n\nIteration 2 of the stressor loop.\n\n## Journey History\n\n- 2026-03-01 · `/restack-journey start` · terrain Greenfield, route discover-stress-decide · D1\n- 2026-03-20 · `/restack-journey iterate` · iterate: two new actors · D2\n",
  },
  "band": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on that have not been verified. A-1 and\nA-2 are asks of people outside the design, A-3 is settled inside it, A-4 is\nresolved.\n\n| ID | Assumption | Source | Validates it | Depends on it | Status | Status date |\n|---|---|---|---|---|---|---|\n| A-1 | Depots open at 06:00 on weekdays | courier interviews | Ask Depot operations: the opening-hours list per depot | ADR-0005 | Open | 2026-03-10 |\n| A-2 | A locker bank survives a 30-second power cut | vendor sheet | Ask Locker vendor: the UPS hold-up time | R2 | Partly resolved | 2026-04-10 |\n| A-3 | Reservation lookups stay under 50 ms | inference | a load test against the staging API | ADR-0003 | Open | 2026-04-06 |\n| A-4 | Couriers carry a phone with mobile data | depot manager | Ask Depot operations: the device policy | ADR-0002 | Resolved | 2026-04-01 |\n\n## Status lines\n\n- A-1 · Open · 2026-03-10 · registered\n- A-2 · Open · 2026-03-22 · registered\n- A-2 · Partly resolved · 2026-04-10 · vendor confirmed a UPS, not its hold-up time\n- A-3 · Open · 2026-04-06 · registered\n- A-4 · Open · 2026-03-12 · registered\n- A-4 · Resolved · 2026-04-01 · depot operations sent the device policy\n",
    "decisions-log.md": "# Decisions Log\n\nEvery gate and every brief, numbered journey-wide.\n\n## D1 · 2026-03-01 · Terrain\n\n- **Gate:** terrain\n- **Answer:** Brownfield\n- **Rationale:** a depot system exists and stays in service.\n- **Changes the actor set:** no\n- **Supersedes:** —\n\n## D2 · 2026-03-20 · Iterate after iteration 1\n\n- **Gate:** iterate\n- **Answer:** iterate\n- **Rationale:** the courier walk found two new actors.\n- **Changes the actor set:** yes\n- **Supersedes:** —\n\n## D3 · 2026-04-18 · Offline unlock: local codes or a cached allow-list?\n\n- **Gate:** brief\n- **Answer:** (open)\n- **Rationale:** —\n- **Changes the actor set:** —\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State: Lockerline\n\n**Last Updated:** 2026-04-20 16:05\n**Terrain Type:** Brownfield\n**Current Phase:** Stressor Analysis\n**Implementation status:** Design-only — nothing implemented\n**Design boundary:** the reservation service and the locker controller; the courier app is a handoff ask\n\n---\n\n## Aspiration\n\nCouriers can drop a parcel at any locker bank, even when the bank is offline.\n\n---\n\n## Current Position\n\n**Where we are:** `/restack-stressor analyze`, iteration 2\n\n**What we've completed:**\n- ✅ `/restack-discover paths` — three paths through the depot\n- ✅ `/restack-stressor walk courier-fill` — two new actors\n\n**What's next:** `/restack-stressor analyze` — score iteration 2 against the new actors before the iterate gate\n\n**Confidence level:** Medium — the controller's offline behaviour is still vendor-reported\n\n---\n\n## Journey History\n\n- 2026-03-01 · `/restack-journey start` · terrain Brownfield, route discover-stress-decide · D1\n- 2026-03-20 · `/restack-journey iterate` · iterate: two new actors · D2\n- 2026-04-18 · `/restack-journey iterate` · gate opened: offline unlock · D3\n",
  },
  "canonical": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on that have not been verified.\n\n| ID | Assumption | Source | Validates it | Depends on it | Status | Status date |\n|---|---|---|---|---|---|---|\n| A-1 | Couriers arrive within 30 minutes of reserving | depot manager | a week of reservation logs | ADR-0002 | Open | 2026-03-10 |\n| A-2 | Locker controllers report door state within a second | vendor sheet | a bench test | ADR-0004 | Open | 2026-04-05 |\n\n## Status lines\n\n- A-1 · Open · 2026-03-10 · registered\n- A-2 · Open · 2026-04-05 · registered\n",
    "decisions-log.md": "# Decisions Log\n\nEvery gate and every brief, numbered journey-wide.\n\n## D1 · 2026-03-01 · Terrain\n\n- **Gate:** terrain\n- **Answer:** Greenfield\n- **Rationale:** no locker system exists yet.\n- **Changes the actor set:** no\n- **Supersedes:** —\n\n## 2026-03-15 · Vendor workshop held, no brief\n\nThe locker vendor walked the controller firmware; notes in discovery. The\nfollow-up is D2.\n\n## D2 · 2026-03-20 · Iterate after iteration 1\n\n- **Gate:** iterate\n- **Answer:** iterate\n- **Rationale:** the courier walk found two new actors.\n- **Changes the actor set:** no\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State: Lockerline\n\n**Implementation status:** Design-only — nothing implemented\n**Design boundary:** the reservation service and the locker controller; the courier app is a handoff ask\n\n## Current Position\n\nIteration 2 of the stressor loop.\n\n## Journey History\n\n- 2026-03-01 · `/restack-journey start` · terrain Greenfield, route discover-stress-decide · D1\n- 2026-03-20 · `/restack-journey iterate` · iterate: two new actors · D2\n",
  },
  "legacy": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on. Created 2026-03-10.\n\n| ID | Assumption the design relies on | Current source | Evidence against / for | Validates it | Spec that depends on it | Status |\n|---|---|---|---|---|---|---|\n| A-01 | Couriers arrive within 30 minutes of reserving | depot manager | **Against:** two depots report 45 minutes | a week of logs | ADR-0002 | **Open: highest leverage** |\n| A-02 | Controllers report door state within a second | vendor sheet | — | a bench test | ADR-0004 | Open |\n\n### Updates 2026-03-25 (bench test)\n- **A-02: FALSIFIED (High).** The bench test measured 4 seconds on firmware 2.1.\n- **A-03 (new):** recipients have a phone that receives SMS. Owner: architect.\n\n### Update 2026-04-02 (iteration 2 walks)\n\n| ID | Unknown | Settles it | Status |\n|---|---|---|---|\n| A-04 | Whether the depot Wi-Fi reaches the back row of lockers | a site survey | Open |\n- A-04 · Partly resolved · 2026-04-03 · survey covered two of three depots\n| A-05 | Whether a parcel can be reassigned while held | the reservation API owner | Recorded |\n| A-06 | The SMS gateway sends within a minute | gateway SLA | depot ops | Open |\n",
    "decisions-log.md": "# Decisions Log\n\n## 2026-03-01: Terrain gate (reconstructed)\n- **Decision:** Greenfield.\n\n## 2026-03-20: D1, iterate after iteration 1\n- **Decision:** iterate.\n- **Rationale:** two new actors.\n\n## 2026-04-02 · Vendor call about firmware 2.1, no brief\n\nFollow-up to D1.\n\n## D2 · 2026-04-05 · Adopt event sourcing\n\n- **Gate:** approach\n- **Answer:** adopt ADR-0003\n- **Rationale:** disputes need history.\n- **Changes the actor set:** yes: added the projection rebuilder. Matrices scored before this are `scored pre-D2`\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State: Lockerline\n\n## Current Position\n\nIteration 2.\n\n## Journey History\n\n| Date | Action | Key Output |\n|---|---|---|\n| 2026-03-01 | Journey started; terrain Greenfield | aspiration defined |\n| 2026-03-20 | `/stressor walk courier-fill` | two new actors |\n\n---\n\n## Known Gaps\n\nThe courier app's offline behaviour is unknown.\n",
  },
  "lived": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on that have not been verified. A-1 and\nA-2 are asks of people outside the design, A-3 is settled inside it, A-4 is\nresolved.\n\n| ID | Assumption | Source | Validates it | Depends on it | Status | Status date |\n|---|---|---|---|---|---|---|\n| A-1 | Depots open at 06:00 on weekdays | courier interviews | Ask Depot operations: the opening-hours list per depot | ADR-0005 | Open | 2026-03-10 |\n| A-2 | A locker bank survives a 30-second power cut | vendor sheet | Ask Locker vendor: the UPS hold-up time | R2 | Partly resolved | 2026-04-10 |\n| A-3 | Reservation lookups stay under 50 ms | inference | a load test against the staging API | ADR-0003 | Open | 2026-04-06 |\n| A-4 | Couriers carry a phone with mobile data | depot manager | Ask Depot operations: the device policy | ADR-0002 | Resolved | 2026-04-01 |\n\n## Status lines\n\n- A-1 · Open · 2026-03-10 · registered\n- A-2 · Open · 2026-03-22 · registered\n- A-2 · Partly resolved · 2026-04-10 · vendor confirmed a UPS, not its hold-up time\n- A-3 · Open · 2026-04-06 · registered\n- A-4 · Open · 2026-03-12 · registered\n- A-4 · Resolved · 2026-04-01 · depot operations sent the device policy\n",
    "decisions-log.md": "# Decisions Log\n\nEvery gate and every brief, numbered journey-wide.\n\n## D1 · 2026-03-01 · Terrain\n\n- **Gate:** terrain\n- **Answer:** Brownfield\n- **Rationale:** a depot system exists and stays in service.\n- **Changes the actor set:** no\n- **Supersedes:** —\n\n## D2 · 2026-03-20 · Iterate after iteration 1\n\n- **Gate:** iterate\n- **Answer:** iterate\n- **Rationale:** the courier walk found two new actors.\n- **Changes the actor set:** yes\n- **Supersedes:** —\n\n## D3 · 2026-04-18 · Offline unlock: local codes or a cached allow-list?\n\n- **Gate:** brief\n- **Answer:** (open)\n- **Rationale:** —\n- **Changes the actor set:** —\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State\n\n**Last Updated:** 2026-04-20\n**Implementation status:** Design-only. Nothing implemented (architect, 2026-04-02: \"paper only\").\n**Design boundary:** the reservation service and the locker controller, ending at the courier app's API (D2). The courier app's internals are handoff asks.\n**Terrain Type:** Greenfield service, but its unlock half is brownfield: it runs inside the existing depot controller chain, which has not been discovered. Reclassification pending D3.\n**Current Phase (2026-04-20, end of session):** Documentation/Review. The review is worked through:\n- **Resolved in the documents:** SYS-1 and SYS-2.\n- **Next ReStack moves when work resumes:** SYS-3 (`/restack-adr update 0007`), then iteration 3.\n**Previous phase line (2026-04-18, `/restack-journey where`):** Stressor loop, iteration 2, parked at D3's trigger.\n**Previous phase line (2026-03-20, after D2):** Discovery. Next: `/restack-stressor walk courier-fill`.\n\n---\n\n## Aspiration\n\nCouriers can drop a parcel at any locker bank, even when the bank is offline.\n\n---\n\n## Current Position\n\n### 2026-04-20 (`/restack-journey where`), supersedes the 2026-03-20 position below\n\n- **Where we are:** iteration 2 scored; the residual ADRs are written; the design loop is parked at D3.\n- **External asks: none sent** (architect, 2026-04-20). Depot operations and the locker vendor hold the open conditions.\n- **Next move:** `/restack-design-review complete`, while the asks are out. Rejected for now: `/restack-journey review`.\n\n### 2026-03-20 (superseded)\n\n- **Where we are:** discovery complete for two paths.\n- **What's next:** `/restack-stressor walk courier-fill`\n- **Confidence level:** Low — the controller is undiscovered\n\n---\n\n## Journey History\n\n- 2026-03-01 · `/restack-journey start` · terrain Greenfield, route discover-stress-decide · D1\n- 2026-03-20 · `/restack-journey iterate` · iterate: two new actors · D2\n- 2026-04-18 · `/restack-journey iterate` · gate opened: offline unlock · D3\n",
  },
}

export const MATRIX_FIXTURES: Readonly<Record<string, string>> = {
  "broken.md": "# A matrix scored with a severity scale\n\n| # | Stressor | Gate | Locker | TOTAL |\n|---|---|---|---|---|\n| 1 | Courier strike | 1 | 2 | 3 |\n| 2 | Heatwave | 0 | 1 | 2 |\n",
  "classify-rj.md": "# Removing RJ: what happens to each row\n\n| Row | Class | Why |\n|---|---|---|\n| S-8 | inherit | a cluster outage still stops whoever replays |\n| S-9 | vanish | the job's misuse goes with the job |\n| S-10 | morph | throttling reaches on-call's manual replay differently |\n\n- S-12: vanish — operators needed a route into the cluster only for the job\n",
  "groups-iter3.md": "# Shared substrates, iteration 3 (Lockerline)\n\nDeclared by the architect on 2026-10-05: what these actors share.\n\n- **event cluster**: EB, SS, RJ\n- on-call tooling: RJ, OC\n",
  "matrix-iter1.md": "# Impact matrix, iteration 1 (Lockerline)\n\n**Scoring baseline:** D2\n\n| Stressor | Lens | CA | RS | LC | NS | Σ |\n|---|---|---|---|---|---|---|\n| S-1 | O | 1 | 1 | · | · | **2** |\n| S-2 | C | · | 1 | 1 | · | **2** |\n| S-3 | O | · | · | · | 1 | **1** |\n| S-4 | C | · | 1 | 1 | · | **2** |\n| S-5 | X | 1 | 1 | 1? | ? | **4** |\n| **Total** | | **2** | **4** | **3** | **2** | **11** |\n",
  "matrix-iter2.md": "# Impact matrix, iteration 2 (Lockerline)\n\n**Scoring baseline:** D3. NS (the SMS sender) is replaced by the event stream;\nPR (the projection rebuilder) is new.\n\n| Stressor | Lens | CA | RS | LC | PR | Σ |\n|---|---|---|---|---|---|---|\n| S-1 | O | 1 | · | · | · | **1** |\n| S-2 | C | · | · | 1 | · | **1** |\n| S-3 | O | 1 | · | · | · | **1** |\n| S-4 | C | · | · | 1 | 1 | **2** |\n| S-5 | X | 1 | 1 | · | · | **2** |\n| S-6 | C | · | 1 | · | 1 | **2** |\n| S-7 | O | · | · | 1 | 1 | **2** |\n| **Total** | | **3** | **2** | **3** | **3** | **11** |\n",
  "matrix-iter3.md": "# Impact matrix, iteration 3 (Lockerline)\n\n**Scoring baseline:** D5. EB (the event broker), SS (the snapshot store) and\nRJ (the replay job) run on one managed event cluster. OC is on-call. Since D6\nthe matrix is `scored pre-D6`.\n\n| Stressor | Lens | CA | RS | LC | PR | EB | SS | RJ | OC | Σ |\n|---|---|---|---|---|---|---|---|---|---|---|\n| S-1 | O | 1 | · | · | · | · | · | · | · | **1** |\n| S-2 | C | · | · | 1 | · | · | · | · | · | **1** |\n| S-3 | O | 1 | · | · | · | · | · | · | · | **1** |\n| S-4 | C | · | · | 1 | 1 | · | · | · | · | **2** |\n| S-5 | X | 1 | 1 | · | · | · | · | · | · | **2** |\n| S-6 | C | · | 1 | · | 1 | 1 | · | · | · | **3** |\n| S-7 | O | · | · | 1 | 1 | · | 1 | · | · | **3** |\n| S-8 | P | · | · | · | · | 1 | 1 | 1 | · | **3** |\n| S-9 | P | 1 | · | · | · | · | · | 1 | 1 | **3** |\n| S-10 | C | · | · | · | · | 1 | · | 1 | 1 | **3** |\n| S-11 | V | · | · | · | · | · | 1 | · | · | **1** |\n| S-12 | C | · | · | · | · | · | · | · | · | **0** |\n| **Total** | | **4** | **2** | **3** | **3** | **3** | **3** | **3** | **2** | **23** |\n",
  "residuals-iter1.md": "# Residuals, iteration 1 (Lockerline)\n\n| Rank | Residual | Cells cleared |\n|---|---|---|\n| 1 | R1 Event-sourced reservations | 3 |\n| 2 | R2 Depot battery backup | 3 |\n\n## R1: Event-sourced reservations\n\nThe reservation service records events instead of updating rows.\n\n**Clears 3 cells:**\n- S-1: RS.\n- S-2: RS.\n- **Outside the cluster:** S-4 (RS; the controller reboot replays from the stream)\n\n**Creates:** the projection rebuilder.\n\n## R2: Depot battery backup\n\n**Clears 3 cells:**\n- S-5: LC, NS.\n- S-3: CA.\n- S-1: RS.\n\n**Leaves:** S-2 (firmware is not a power problem).\n",
  "residuals-iter2.md": "# Residuals, iteration 2 (Lockerline)\n\n## R4: Snapshot store\n\n**Clears 2 cells:**\n- S-4: RS.\n- **Outside the cluster:** S-13 (CA; a stressor retired at D5)\n\n## R5: Replay job\n\nOperators replay the event stream from a job instead of by hand.\n\n**Clears 4 cells:**\n- S-1: RS.\n- S-4: RS.\n- S-12: OC.\n- S-3: BG.\n\n**Creates:** the replay job, and a route for operators into the event cluster.\n",
  "unfinished.md": "# A scored matrix whose margins were never filled in\n\n| # | Stressor | Gate | Locker | TOTAL |\n|---|---|---|---|---|\n| 1 | Courier strike | 1 | 1 | |\n| 2 | Heatwave | 0 | 1 | 5 |\n| 3 | Vandalism | · | 1? | |\n",
}
