// AUTO-GENERATED from tests/fixtures/journey/ by scripts/gen_skills.py - do not edit.
// The journeys journey.py is tested against, so the mod reads the same shapes.

export const FIXTURES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "asks": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on that have not been verified. A-1 to\nA-3 and A-7 are asks of people outside the design; A-5 reads like one but has\nnot been routed; A-6 is settled inside it.\n\n| ID | Assumption | Source | Validates it | Depends on it | Status | Status date |\n|---|---|---|---|---|---|---|\n| A-1 | Depots open at 06:00 on weekdays | courier interviews | Ask Depot operations: the opening-hours list per depot | ADR-0005 | Open | 2026-03-10 |\n| A-2 | Locker controllers report door state within a second | vendor sheet | Ask Locker vendor: the firmware's reporting interval | ADR-0004, S-12 | Open | 2026-03-20 |\n| A-3 | A locker bank survives a 30-second power cut | vendor sheet | Ask Locker vendor team: the UPS hold-up time | R2 | Partly resolved | 2026-04-10 |\n| A-4 | Couriers carry a phone with mobile data | depot manager | Ask Depot operations: the device policy | ADR-0002 | Resolved | 2026-04-01 |\n| A-5 | Parcel labels carry the locker bank ID | label sample | confirm with the courier partner's integration owner | ADR-0006 | Open | 2026-04-05 |\n| A-6 | Reservation lookups stay under 50 ms | inference | a load test against the staging API | ADR-0003 | Open | 2026-04-06 |\n| A-7 | Door unlock codes are single use | design | Ask Security: a pen test of the unlock endpoint | R1 | Resolved by design (test pending) | 2026-04-08 |\n\n## Status lines\n\n- A-1 · Open · 2026-03-10 · registered\n- A-2 · Open · 2026-03-20 · registered\n- A-2 · Open · 2026-04-02 · asked Locker vendor\n- A-3 · Open · 2026-03-22 · registered\n- A-3 · Open · 2026-03-25 · asked Locker vendor team\n- A-3 · Partly resolved · 2026-04-10 · vendor confirmed a UPS, not its hold-up time\n- A-3 · Partly resolved · 2026-04-15 · asked Locker vendor team\n- A-4 · Open · 2026-03-12 · registered\n- A-4 · Resolved · 2026-04-01 · depot operations sent the device policy\n- A-5 · Open · 2026-04-05 · registered\n- A-6 · Open · 2026-04-06 · registered\n- A-7 · Open · 2026-04-07 · registered\n- A-7 · Resolved by design (test pending) · 2026-04-08 · single-use codes in the design\n",
    "decisions-log.md": "# Decisions Log\n\nEvery gate and every brief, numbered journey-wide.\n\n## D1 · 2026-03-01 · Terrain\n\n- **Gate:** terrain\n- **Answer:** Greenfield\n- **Rationale:** no locker system exists yet.\n- **Changes the actor set:** no\n- **Supersedes:** —\n\n## 2026-03-15 · Vendor workshop held, no brief\n\nThe locker vendor walked the controller firmware; notes in discovery. The\nfollow-up is D2.\n\n## D2 · 2026-03-20 · Iterate after iteration 1\n\n- **Gate:** iterate\n- **Answer:** iterate\n- **Rationale:** the courier walk found two new actors.\n- **Changes the actor set:** no\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State: Lockerline\n\n**Implementation status:** Design-only — nothing implemented\n**Design boundary:** the reservation service and the locker controller; the courier app is a handoff ask\n\n## Current Position\n\nIteration 2 of the stressor loop.\n\n## Journey History\n\n- 2026-03-01 · `/restack-journey start` · terrain Greenfield, route discover-stress-decide · D1\n- 2026-03-20 · `/restack-journey iterate` · iterate: two new actors · D2\n",
  },
  "band": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on that have not been verified. A-1 and\nA-2 are asks of people outside the design, A-3 is settled inside it, A-4 is\nresolved.\n\n| ID | Assumption | Source | Validates it | Depends on it | Status | Status date |\n|---|---|---|---|---|---|---|\n| A-1 | Depots open at 06:00 on weekdays | courier interviews | Ask Depot operations: the opening-hours list per depot | ADR-0005 | Open | 2026-03-10 |\n| A-2 | A locker bank survives a 30-second power cut | vendor sheet | Ask Locker vendor: the UPS hold-up time | R2 | Partly resolved | 2026-04-10 |\n| A-3 | Reservation lookups stay under 50 ms | inference | a load test against the staging API | ADR-0003 | Open | 2026-04-06 |\n| A-4 | Couriers carry a phone with mobile data | depot manager | Ask Depot operations: the device policy | ADR-0002 | Resolved | 2026-04-01 |\n\n## Status lines\n\n- A-1 · Open · 2026-03-10 · registered\n- A-2 · Open · 2026-03-22 · registered\n- A-2 · Partly resolved · 2026-04-10 · vendor confirmed a UPS, not its hold-up time\n- A-3 · Open · 2026-04-06 · registered\n- A-4 · Open · 2026-03-12 · registered\n- A-4 · Resolved · 2026-04-01 · depot operations sent the device policy\n",
    "decisions-log.md": "# Decisions Log\n\nEvery gate and every brief, numbered journey-wide.\n\n## D1 · 2026-03-01 · Terrain\n\n- **Gate:** terrain\n- **Answer:** Brownfield\n- **Rationale:** a depot system exists and stays in service.\n- **Changes the actor set:** no\n- **Supersedes:** —\n\n## D2 · 2026-03-20 · Iterate after iteration 1\n\n- **Gate:** iterate\n- **Answer:** iterate\n- **Rationale:** the courier walk found two new actors.\n- **Changes the actor set:** yes\n- **Supersedes:** —\n\n## D3 · 2026-04-18 · Offline unlock: local codes or a cached allow-list?\n\n- **Gate:** brief\n- **Answer:** (open)\n- **Rationale:** —\n- **Changes the actor set:** —\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State: Lockerline\n\n**Last Updated:** 2026-04-20 16:05\n**Terrain Type:** Brownfield\n**Current Phase:** Stressor Analysis\n**Implementation status:** Design-only — nothing implemented\n**Design boundary:** the reservation service and the locker controller; the courier app is a handoff ask\n\n---\n\n## Aspiration\n\nCouriers can drop a parcel at any locker bank, even when the bank is offline.\n\n---\n\n## Current Position\n\n**Where we are:** `/restack-stressor analyze`, iteration 2\n\n**What we've completed:**\n- ✅ `/restack-discover paths` — three paths through the depot\n- ✅ `/restack-stressor walk courier-fill` — two new actors\n\n**What's next:** `/restack-stressor analyze` — score iteration 2 against the new actors before the iterate gate\n\n**Confidence level:** Medium — the controller's offline behaviour is still vendor-reported\n\n---\n\n## Journey History\n\n- 2026-03-01 · `/restack-journey start` · terrain Brownfield, route discover-stress-decide · D1\n- 2026-03-20 · `/restack-journey iterate` · iterate: two new actors · D2\n- 2026-04-18 · `/restack-journey iterate` · gate opened: offline unlock · D3\n",
  },
  "canonical": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on that have not been verified.\n\n| ID | Assumption | Source | Validates it | Depends on it | Status | Status date |\n|---|---|---|---|---|---|---|\n| A-1 | Couriers arrive within 30 minutes of reserving | depot manager | a week of reservation logs | ADR-0002 | Open | 2026-03-10 |\n| A-2 | Locker controllers report door state within a second | vendor sheet | a bench test | ADR-0004 | Open | 2026-04-05 |\n\n## Status lines\n\n- A-1 · Open · 2026-03-10 · registered\n- A-2 · Open · 2026-04-05 · registered\n",
    "decisions-log.md": "# Decisions Log\n\nEvery gate and every brief, numbered journey-wide.\n\n## D1 · 2026-03-01 · Terrain\n\n- **Gate:** terrain\n- **Answer:** Greenfield\n- **Rationale:** no locker system exists yet.\n- **Changes the actor set:** no\n- **Supersedes:** —\n\n## 2026-03-15 · Vendor workshop held, no brief\n\nThe locker vendor walked the controller firmware; notes in discovery. The\nfollow-up is D2.\n\n## D2 · 2026-03-20 · Iterate after iteration 1\n\n- **Gate:** iterate\n- **Answer:** iterate\n- **Rationale:** the courier walk found two new actors.\n- **Changes the actor set:** no\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State: Lockerline\n\n**Implementation status:** Design-only — nothing implemented\n**Design boundary:** the reservation service and the locker controller; the courier app is a handoff ask\n\n## Current Position\n\nIteration 2 of the stressor loop.\n\n## Journey History\n\n- 2026-03-01 · `/restack-journey start` · terrain Greenfield, route discover-stress-decide · D1\n- 2026-03-20 · `/restack-journey iterate` · iterate: two new actors · D2\n",
  },
  "legacy": {
    "assumptions-register.md": "# Assumptions Register\n\nBeliefs the Lockerline design relies on. Created 2026-03-10.\n\n| ID | Assumption the design relies on | Current source | Evidence against / for | Validates it | Spec that depends on it | Status |\n|---|---|---|---|---|---|---|\n| A-01 | Couriers arrive within 30 minutes of reserving | depot manager | **Against:** two depots report 45 minutes | a week of logs | ADR-0002 | **Open: highest leverage** |\n| A-02 | Controllers report door state within a second | vendor sheet | — | a bench test | ADR-0004 | Open |\n\n### Updates 2026-03-25 (bench test)\n- **A-02: FALSIFIED (High).** The bench test measured 4 seconds on firmware 2.1.\n- **A-03 (new):** recipients have a phone that receives SMS. Owner: architect.\n\n### Update 2026-04-02 (iteration 2 walks)\n\n| ID | Unknown | Settles it | Status |\n|---|---|---|---|\n| A-04 | Whether the depot Wi-Fi reaches the back row of lockers | a site survey | Open |\n- A-04 · Partly resolved · 2026-04-03 · survey covered two of three depots\n| A-05 | Whether a parcel can be reassigned while held | the reservation API owner | Recorded |\n| A-06 | The SMS gateway sends within a minute | gateway SLA | depot ops | Open |\n",
    "decisions-log.md": "# Decisions Log\n\n## 2026-03-01: Terrain gate (reconstructed)\n- **Decision:** Greenfield.\n\n## 2026-03-20: D1, iterate after iteration 1\n- **Decision:** iterate.\n- **Rationale:** two new actors.\n\n## 2026-04-02 · Vendor call about firmware 2.1, no brief\n\nFollow-up to D1.\n\n## D2 · 2026-04-05 · Adopt event sourcing\n\n- **Gate:** approach\n- **Answer:** adopt ADR-0003\n- **Rationale:** disputes need history.\n- **Changes the actor set:** yes: added the projection rebuilder. Matrices scored before this are `scored pre-D2`\n- **Supersedes:** —\n",
    "journey-state.md": "# Journey State: Lockerline\n\n## Current Position\n\nIteration 2.\n\n## Journey History\n\n| Date | Action | Key Output |\n|---|---|---|\n| 2026-03-01 | Journey started; terrain Greenfield | aspiration defined |\n| 2026-03-20 | `/stressor walk courier-fill` | two new actors |\n\n---\n\n## Known Gaps\n\nThe courier app's offline behaviour is unknown.\n",
  },
}
