#!/usr/bin/env python3
"""Generate skills/<name>/SKILL.md from skills/<name>/SKILL.md.tmpl.

A skill's SKILL.md is a build artifact. The template is the source of truth;
shared behaviour lives in scripts/preamble/ and is composed in by tier, so a
change to how decision briefs work is made once rather than fourteen times.

Usage:
    python scripts/gen_skills.py            # regenerate every skill that has a template
    python scripts/gen_skills.py journey    # regenerate named skills only
    python scripts/gen_skills.py --check    # verify on-disk output matches (exit 1 on drift)

Also renders tests/fixtures/journey/ into mods/restack-view/tests/fixtures.ts,
when no skill is named, so the mod is tested against the same journeys.

Macros (resolved recursively, {{NAME}} or {{NAME:arg}}):
    {{PREAMBLE}}            shared behaviour for the tier declared in frontmatter
    {{SECTION_INDEX}}       table of this skill's on-demand sections
    {{SECTION:<id>}}        inline a section verbatim
    {{SECTION_SELF_CHECK}}  end-of-run reminder to actually read the sections

Shared sections ("shared": true -> scripts/shared/) and canonical templates
("source": "templates/<file>") are vendored: each consuming skill gets a
generated copy in its own sections/ directory, so the installed skill is
self-contained. setup copies skills/restack-*/ and nothing else, so a file that
lives only in scripts/shared/ or templates/ is never installed - which is how
the outside opinion silently stopped running.

Standard library only, by design: the toolkit already asks contributors for
Python, and a generator that needs its own install is a generator people skip.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
PREAMBLE = ROOT / "scripts" / "preamble"
JOURNEY_FIXTURES = ROOT / "tests" / "fixtures" / "journey"
# A mod's tests cannot read files, so the journeys journey.py is tested against
# are rendered into a module the mod's tests import (ADR-029, decision point 4).
MOD_FIXTURES = ROOT / "mods" / "restack-view" / "tests" / "fixtures.ts"

BANNER = (
    "<!-- AUTO-GENERATED from SKILL.md.tmpl - do not edit this file directly. -->\n"
    "<!-- Edit the template or scripts/preamble/*, then: python scripts/gen_skills.py -->"
)

# Every section path a generated skill names is written against <base>, the
# skill's own directory. A repo-relative path (skills/<name>/sections/...,
# scripts/shared/...) resolves in this checkout and nowhere else.
BASE = "<base>"

MACRO = re.compile(r"\{\{([A-Z_]+)(?::([^}]+))?\}\}")
MAX_DEPTH = 5


class BuildError(Exception):
    pass


def split_frontmatter(text: str, origin: Path) -> tuple[str, str]:
    """Return (frontmatter_block, body). Frontmatter is passed through verbatim."""
    if not text.startswith("---\n"):
        raise BuildError(f"{origin}: template must open with a YAML frontmatter block")
    end = text.find("\n---\n", 3)
    if end == -1:
        raise BuildError(f"{origin}: unterminated frontmatter block")
    return text[: end + 5], text[end + 5:]


def read_tier(frontmatter: str, origin: Path) -> int:
    match = re.search(r"^preamble-tier:\s*(\d+)\s*$", frontmatter, re.MULTILINE)
    if not match:
        raise BuildError(
            f"{origin}: missing 'preamble-tier: N' in frontmatter. Every template "
            f"that resolves the PREAMBLE macro must declare its tier (1-3)."
        )
    tier = int(match.group(1))
    if tier not in (1, 2, 3):
        raise BuildError(f"{origin}: preamble-tier must be 1, 2 or 3 (got {tier})")
    return tier


def build_preamble(tier: int) -> str:
    manifest = json.loads((PREAMBLE / "manifest.json").read_text(encoding="utf-8"))
    wanted: set[str] = set()
    for level in range(1, tier + 1):
        wanted.update(manifest["tiers"][str(level)]["fragments"])
    ordered = [name for name in manifest["order"] if name in wanted]

    missing = wanted - set(ordered)
    if missing:
        raise BuildError(
            f"preamble/manifest.json: fragment(s) {sorted(missing)} are in a tier "
            f"but absent from 'order' - add them so composition stays deterministic"
        )

    parts = []
    for name in ordered:
        path = PREAMBLE / name
        if not path.exists():
            raise BuildError(f"preamble/manifest.json references missing fragment {name}")
        parts.append(path.read_text(encoding="utf-8").strip())
    return "\n\n---\n\n".join(parts)


SHARED_SECTIONS = ROOT / "scripts" / "shared"


def vendored_source(entry: dict) -> str | None:
    """Repo-relative source of a vendored section, or None for an owned one.

    "shared": true    -> scripts/shared/<file>  (method several skills use)
    "source": "<path>" -> any repo file, e.g. templates/journey-state-template.md
                          (a canonical format a skill writes against)
    """
    if entry.get("source"):
        return entry["source"]
    if entry.get("shared"):
        return f"scripts/shared/{entry['file']}"
    return None


def vendored_copy(entry: dict) -> str:
    """A vendored section as it is installed: the source plus a generated banner."""
    rel = vendored_source(entry)
    source = ROOT / rel
    if not source.exists():
        raise BuildError(f"section {entry['file']} is vendored from {rel}, which does not exist")
    banner = (
        f"<!-- AUTO-GENERATED copy of {rel} - do not edit this file directly. -->\n"
        f"<!-- Edit {rel}, then: python scripts/gen_skills.py -->\n"
    )
    return banner + source.read_text(encoding="utf-8")


def section_path(skill_dir: Path, entry: dict) -> Path:
    """Where a section's content lives.

    A section is normally owned by one skill and sits in its sections/ dir.
    A vendored one (shared method, or a canonical template) lives elsewhere in
    the repo, because several skills need it and duplicating it would
    reintroduce the two-sources-of-truth problem the templates exist to remove.
    """
    rel = vendored_source(entry)
    if rel:
        return ROOT / rel
    return skill_dir / "sections" / entry["file"]


def load_sections(skill_dir: Path) -> list[dict]:
    manifest_path = skill_dir / "sections" / "manifest.json"
    if not manifest_path.exists():
        return []
    return json.loads(manifest_path.read_text(encoding="utf-8"))["sections"]


def render_section_index(skill_dir: Path, sections: list[dict]) -> str:
    if not sections:
        return ""
    lines = [
        "## Section index - read each section when its situation applies",
        "",
        "These sections are not loaded with this file. Read the section file with",
        "the Read tool at the moment its situation applies, and work from it - not",
        "from memory of what it probably says. `<base>` is this skill's base",
        "directory - see *Paths and shell* in the preamble; if no base directory was",
        f"printed, it is `~/.claude/skills/{skill_dir.name}`.",
        "",
        "| Read this | When |",
        "|---|---|",
    ]
    for section in sections:
        lines.append(f"| `{BASE}/sections/{section['file']}` | {section['trigger']} |")
    return "\n".join(lines)


def render_self_check(sections: list[dict]) -> str:
    if not sections:
        return ""
    names = ", ".join(f"`{s['file']}`" for s in sections)
    return (
        "## Section self-check (before you finish)\n\n"
        "Confirm you actually read every section the index named as applying to "
        "this run, and executed it in full. The sections are where the method "
        f"lives ({names}) - running one from memory produces output with the "
        "right shape and none of the teeth. If you skipped one, stop and read it now."
    )


def resolve(text: str, skill_dir: Path, tier: int, origin: Path) -> str:
    sections = load_sections(skill_dir)
    by_id = {s["id"]: s for s in sections}

    def substitute(match: "re.Match[str]") -> str:
        name, arg = match.group(1), match.group(2)
        if name == "PREAMBLE":
            return build_preamble(tier)
        if name == "SECTION_INDEX":
            return render_section_index(skill_dir, sections)
        if name == "SECTION_SELF_CHECK":
            return render_self_check(sections)
        if name == "SECTION":
            if arg not in by_id:
                known = ", ".join(sorted(by_id)) or "none declared"
                raise BuildError(
                    f"{origin}: section '{arg}' is not in sections/manifest.json (have: {known})"
                )
            return section_path(skill_dir, by_id[arg]).read_text(encoding="utf-8").strip()
        raise BuildError(f"{origin}: unknown macro '{name}'")

    for _ in range(MAX_DEPTH):
        expanded = MACRO.sub(substitute, text)
        if expanded == text:
            return expanded
        text = expanded
    raise BuildError(f"{origin}: macro expansion did not settle after {MAX_DEPTH} passes (cycle?)")


def render(template_path: Path) -> str:
    raw = template_path.read_text(encoding="utf-8")
    skill_dir = template_path.parent
    frontmatter, body = split_frontmatter(raw, template_path)
    tier = read_tier(frontmatter, template_path)
    body = resolve(body, skill_dir, tier, template_path)
    body = re.sub(r"\n{4,}", "\n\n\n", body)
    return f"{frontmatter}{BANNER}\n{body.rstrip()}\n"


def render_mod_fixtures() -> str:
    """tests/fixtures/journey/<name>/journey/<file> as one TypeScript module."""
    journeys: dict[str, dict[str, str]] = {}
    for path in sorted(JOURNEY_FIXTURES.glob("*/journey/*.md")):
        text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        journeys.setdefault(path.parent.parent.name, {})[path.name] = text
    out = [
        "// AUTO-GENERATED from tests/fixtures/journey/ by scripts/gen_skills.py - do not edit.",
        "// The journeys journey.py is tested against, so the mod reads the same shapes.",
        "",
        "export const FIXTURES: Readonly<Record<string, Readonly<Record<string, string>>>> = {",
    ]
    for name, files in journeys.items():
        out.append(f"  {json.dumps(name)}: {{")
        for file, text in files.items():
            out.append(f"    {json.dumps(file)}: {json.dumps(text, ensure_ascii=False)},")
        out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    # `journey` and `restack-journey` both work; the docs use the short form.
    names = [a if a.startswith("restack-") else f"restack-{a}" for a in argv if not a.startswith("-")]

    templates = sorted(SKILLS.glob("*/SKILL.md.tmpl"))
    if names:
        templates = [t for t in templates if t.parent.name in names]
        unknown = set(names) - {t.parent.name for t in templates}
        if unknown:
            print(f"no template for: {', '.join(sorted(unknown))}", file=sys.stderr)
            return 1
    if not templates:
        print("no SKILL.md.tmpl found under skills/", file=sys.stderr)
        return 1

    drifted, written = [], []
    if not names and MOD_FIXTURES.parent.is_dir():
        current = MOD_FIXTURES.read_text(encoding="utf-8") if MOD_FIXTURES.exists() else None
        output = render_mod_fixtures()
        if current != output:
            if check:
                drifted.append(MOD_FIXTURES.relative_to(ROOT))
            else:
                MOD_FIXTURES.write_text(output, encoding="utf-8", newline="\n")
                written.append(MOD_FIXTURES.relative_to(ROOT))
    for template in templates:
        try:
            outputs = {template.parent / "SKILL.md": render(template)}
            for entry in load_sections(template.parent):
                if vendored_source(entry):
                    outputs[template.parent / "sections" / entry["file"]] = vendored_copy(entry)
        except BuildError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
        for target, output in outputs.items():
            current = target.read_text(encoding="utf-8") if target.exists() else None
            if current == output:
                continue
            if check:
                drifted.append(target.relative_to(ROOT))
            else:
                target.write_text(output, encoding="utf-8", newline="\n")
                written.append(target.relative_to(ROOT))

    if check:
        if drifted:
            print("generated file(s) out of date with their source:", file=sys.stderr)
            for path in drifted:
                print(f"  {path}", file=sys.stderr)
            print("\nrun: python scripts/gen_skills.py", file=sys.stderr)
            return 1
        print(f"up to date ({len(templates)} template(s) checked)")
        return 0

    for path in written:
        print(f"generated {path}")
    print(f"{len(written)} file(s) written from {len(templates)} template(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
